# Generated by Django 3.1.5 on 2021-01-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='questions',
            field=models.ManyToManyField(to='main.Question'),
        ),
    ]
